# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=200)),
                ('pub_date', models.DateField()),
                ('vote_count', models.IntegerField()),
            ],
        ),
    ]
